Pumas nt2 bigg v2
ESCOMP/PUMAS pull request #42
Opened 2022-05-27 20:55 UTC by cacraigucar

Add refl10cm and reflz10cm diagnostics

Tested with ERP_D_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.F2000dev.cheyenne_intel.cam-outfrq9s

2022-05-28 03:00 UTC, sjsprecious commented
@cacraigucar Thanks for this PR. I have a few minor comments related to the OpenACC directives. Should I commit directly to your branch or leave a comment here?

2022-05-31 19:28 UTC, cacraigucar commented
> 

There are two ways to move forward (since @andrewgettelman tested with this).

1. We go ahead and commit my changes as is and then @sjsprecious makes his changes directly in PUMAS.  @Katetc makes a tag after the two commits are done.
2. @sjsprecious opens a PR back to my branch, I bring the changes in and we commit them all together to PUMAS

Since @andrewgettelman has tested and I'd like to make sure the answers don't change from that run since he won't be able to run another test for a number of weeks, I prefer 1.  That way I can make sure answers don't change.  Thoughts?

2022-05-31 19:31 UTC, Katetc commented
If the notes are just related to ACC directives, then they won't change answers in a standard CPU run. I'm curious to see if his issues are related to the merge after his tag. Jian, could you please put your comments in this PR. If they are minimal, we can get them ironed out for this tag.

2022-06-01 00:05 UTC, sjsprecious requested changes

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +  !$acc               areflz,frefl,csrfl,acsrfl,fcsrfl,refl10cm,reflz10cm,rercld,ncai,ncal,      &
I would suggest aligning the openacc directives by the `&` sign. If you think it is too tedious to change every line below, maybe just move `refl10cm` and `reflz10cm` after `nmeltgtot`.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +
Add `!$acc end parallel` directive here.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +
Add `!$acc end parallel` here.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +
Add `!$acc parallel vector_length(VLENS) default(present)` here.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +
Add `!$acc parallel vector_length(VLENS) default(present)` here.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +  !$acc loop gang vector collapse(2) private(dum,dum1)
Remove `private(dum,dum1)`.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +  !$acc loop gang vector collapse(2) private(dum,dum1)
Remove `private(dum,dum1)`.

2022-06-01 00:05 UTC, sjsprecious commented on micro_pumas_v1.F90
> +     do i=1,mgncol
Remove these lines and only keep the `!redefine fice here` comment.

2022-06-01 00:18 UTC, sjsprecious commented
Hi @cacraigucar and @Katetc , thanks for your comments. I just left the comments at the places where I think some GPU directive changes are needed. They are not answer-changing either on CPU or GPU, but really a requirement for a consistent coding style. I think they can go in as the same tag as Cheryl's changes here but let me know if you have any questions.

2022-06-02 17:40 UTC, Katetc approved these changes

2022-06-02 17:40 UTC, merged